language: node_js
node_js:
  - 10
before_install:
    - cd ui
    - npm install -g yarn
install:
    - yarn install
script:
    - yarn lint
    - yarn build
cache:
    npm: true
    yarn: true
git:
  depth: 1
