on: [push, pull_request]

name: ci

jobs:
  unit-test:
    name: unit-test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]
        project: [server, client]
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
      - run: cargo test --verbose --all
        working-directory: ${{ matrix.project }}
  static-analysis:
    name: static-analysis
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [server, client]
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2019-11-06
          override: true
          profile: minimal
          components: clippy, rustfmt
      - run: cargo fmt -- --check
        working-directory: ${{ matrix.project }}
      - run: cargo check
        working-directory: ${{ matrix.project }}
      - run: cargo clippy --all --all-targets -- -D warnings
        working-directory: ${{ matrix.project }}
